/**
 * UI 文案常量（M7：为 i18n 铺路）。
 * 规则：界面静态文案一律引用本文件常量，组件内不得硬编码字符串（AGENTS §6b）。
 */

export const app = {
  title: "Another Tavern",
  pages: {
    chat: "聊天",
    characters: "角色卡",
    lorebooks: "世界书",
    plans: "计划",
    regex: "正则",
    settings: "设置",
  },
  openSidebar: "打开会话列表",
};

export const sidebar = {
  newSession: "前往聊天",
  newGroup: "＋ 新建群聊",
  groupTitle: "新建群聊",
  groupTitlePlaceholder: "群聊名称（可选）",
  chooseMembers: "选择角色（至少 2 个）",
  atLeastTwoMembers: "群聊至少需要两个角色。",
  selectedMembers: (n: number): string => `已选 ${n} 个角色`,
  moveUp: "上移",
  moveDown: "下移",
  removeMember: "移除成员",
  createGroup: "创建群聊",
  creatingGroup: "创建中…",
  close: "关闭",
  groupCreateFailed: "创建群聊失败：",
  deleteSession: "删除会话",
  empty: "还没有会话",
};

export const chat = {
  untitledSession: "会话",
  streamingPlaceholder: "…",
  pickSession: "从左侧选择一个会话，或在「角色卡」页新建会话。",
  viewLastPrompt: "查看本次最终 prompt",
  planLabel: "计划：",
  followGlobalDefault: (name: string): string => `跟随全局默认（${name}）`,
  builtinDefault: "内置默认",
  loreSources: (linked: number, global: number): string =>
    `世界书：卡内 + 挂载 ${linked} · 全局 ${global}`,
  noPromptYet: "尚未组装（发送一条消息后这里显示最终 prompt）。",
  inputPlaceholder: "输入消息…（Enter 发送，Shift+Enter 换行）",
  send: "发送",
  regenerate: "重新生成",
  groupBadge: "群聊",
  groupMembers: (n: number): string => `${n} 位角色`,
  currentSpeaker: "当前发言角色：",
  automaticSpeaker: "自动轮换",
  forceSpeaker: "允许静音角色发言",
  muted: "静音",
  memberSettings: "成员设置",
  moveUp: "上移",
  moveDown: "下移",
  removeMember: "移除成员",
  groupSettingsTitle: "群聊设置",
  replyStrategy: "发言策略",
  manualStrategy: "手动选择",
  listStrategy: "按列表轮换",
  scenarioOverride: "群聊场景覆盖",
  scenarioPlaceholder: "留空则沿用角色场景",
  allowSelfResponses: "允许角色连续发言",
  saveGroupSettings: "保存群聊设置",
  saving: "保存中…",
  groupSettingsSaved: "群聊设置已保存 ✓",
  groupSettingsFailed: "保存群聊设置失败：",
  atLeastTwoMembers: "群聊至少需要两个角色。",
  streamingAs: (name: string): string => `${name} 正在回复…`,
  memberMuted: "已静音",
  edit: "编辑",
  save: "保存",
  cancel: "取消",
};

export const messageItem = {
  prevCandidate: "上一个候选",
  nextCandidate: "下一个候选",
  newCandidate: "生成新候选",
  pending: "等待生成",
  failed: "生成失败",
  cancelled: "已取消",
  retry: "重试",
};

export const characters = {
  dropHint: "拖拽 PNG / JSON 角色卡到此处",
  pickFile: "或选择文件导入",
  importing: "导入中：",
  imported: (name: string): string => `已导入：${name}`,
  importFailed: "导入失败：",
  edit: "编辑",
  save: "保存",
  startChat: "开始聊天",
  empty: "还没有角色卡，先导入一张。",
  loading: "加载中…",
  saved: "已保存。",
  saveFailed: "保存失败：",
  createSessionFailed: "建会话失败：",
  cancel: "取消",
  form: {
    name: "名字",
    description: "描述",
    personality: "性格",
    scenario: "场景",
    firstMes: "开场白",
  },
};

export const settings = {
  title: "设置",
  baseUrl: "上游 baseUrl",
  baseUrlPlaceholder: "https://api.example.com/v1",
  apiKey: "API key",
  apiKeyLabel: (has: boolean): string => `API key（${has ? "已配置" : "未配置"}；留空保留原值）`,
  model: "模型",
  modelPlaceholder: "gpt-4o",
  samplingLegend: "采样参数（留空 = 不发送该参数）",
  temperature: "temperature",
  topP: "top_p",
  maxTokens: "max_tokens",
  frequencyPenalty: "frequency_penalty",
  presencePenalty: "presence_penalty",
  stop: "stop",
  seed: "seed",
  save: "保存",
  saved: "已保存（API key 不回显明文）✓",
  saveFailed: "保存失败：",
};

export const regex = {
  title: "正则脚本",
  description: "按顺序处理用户输入、AI 输出或最终 Prompt；原始聊天记录不会被改写。",
  globalRules: "全局规则",
  newRule: "新建规则",
  pickRule: "从左侧选择一条规则，或新建规则。",
  empty: "还没有全局正则规则。",
  loading: "加载中…",
  name: "名称",
  findRegex: "查找正则",
  replaceString: "替换文本",
  trimStrings: "从捕获结果移除（每行一项）",
  placementsTitle: "作用位置",
  placements: {
    userInput: "用户输入",
    aiOutput: "AI 输出",
    prompt: "Prompt",
    worldInfo: "世界书",
    markdown: "Markdown",
  },
  enabled: "启用",
  disabled: "停用",
  delete: "删除",
  save: "保存",
  cancel: "取消",
  saved: "已保存 ✓",
  deleted: "已删除 ✓",
  saveFailed: "保存失败：",
  nameRequired: "规则名称不能为空。",
  placementRequired: "至少选择一个作用位置。",
  testInput: "测试输入",
  test: "测试规则",
  tested: "测试完成 ✓",
  testFailed: "测试失败：",
  scopeNote:
    "角色卡中的 extensions.regex_scripts 与预设中的同名扩展会自动参与聊天；本页管理全局规则。",
};

export const lorebooks = {
  importSt: "导入 ST 世界书 JSON",
  importStGlobal: "导入并设为全局",
  importing: "（处理中…）",
  newBook: "＋ 新建世界书",
  noBooks: "还没有世界书",
  importSummary: "导入摘要：",
  entryCount: (n: number): string => `条目数：${n}`,
  warningsKept: (n: number): string => `警告 ${n} 条（未知字段已保留）`,
  bookName: "书名",
  tokenBudget: "token 预算（留空 = 全局 25%）",
  tokenBudgetPlaceholder: "2048",
  scanDepth: "扫描深度",
  scanDepthPlaceholder: "2",
  globalBook: "全局书",
  mountTo: "挂载到角色",
  entries: (n: number): string => `条目（${n}）`,
  newEntry: "＋ 新建条目",
  deleteBook: "删除本书",
  noEntries: "暂无条目",
  entryEditor: "条目编辑",
  keys: "主关键词（逗号分隔）",
  secondaryKeys: "副关键词（逗号分隔；selective 开启时生效）",
  content: "内容",
  constant: "常驻（无视关键词）",
  enabled: "启用",
  useSecondary: "启用副关键词",
  preventRecursion: "阻止递归",
  insertionOrder: "插入顺序",
  position: "插入位置",
  depth: "深度（atDepth）",
  saveEntry: "保存条目",
  positions: {
    beforeChar: "角色描述前",
    afterChar: "角色描述后",
    atDepth: "历史深度注入",
    anTop: "作者注上（不支持）",
    anBottom: "作者注下（不支持）",
    beforeExample: "示例前（不支持）",
    afterExample: "示例后（不支持）",
    outlet: "Outlet（不支持）",
  },
  pickBook: "从左侧选择或导入一本世界书。",
  importingStatus: "导入中…",
  importDone: "导入完成 ✓（摘要见下方）",
  importFailed: "导入失败：",
  entrySaved: "条目已保存 ✓",
  saveFailed: "保存失败：",
  autoName: (time: string): string => `世界书 ${time}`,
  globalBadge: "[全局]",
  edit: "编辑",
  deleteEntry: "删除",
  constantBadge: "常驻",
  close: "关闭",
  cancel: "取消",
};

export const plans = {
  importSt: "导入 ST 预设 JSON",
  importSummary: "映射结果：",
  enabledSlots: (ids: string): string => `启用槽位：${ids}`,
  disabledSlots: (ids: string): string => `禁用槽位：${ids}`,
  dropped: (list: string): string => `未映射/丢弃：${list}`,
  newPlan: "＋ 新建计划",
  noPlans: "还没有计划",
  setGlobalDefault: "设为全局默认",
  setGlobalDefaultDone: "已设为全局默认 ✓",
  followGlobalDefault: (name: string): string => `全局默认（${name}）`,
  phi: "Post-History Instructions（历史后注入）",
  savePlan: "保存计划",
  deletePlan: "删除计划",
  defaultSource: "默认来源",
  customText: "自定义文本",
  customPlaceholder: "自定义内容（支持 {{char}} / {{user}} 宏）",
  enabled: "启用",
  pickPlan: "从左侧选择或导入一个组装计划。",
  slotLabels: {
    main: "主提示 (main)",
    wiBefore: "世界书·前",
    persona: "用户人设",
    description: "角色描述",
    personality: "性格摘要",
    scenario: "场景",
    wiAfter: "世界书·后",
    examples: "对话示例",
  },
  importingStatus: "导入中…",
  importDone: "导入完成 ✓（映射摘要见左侧）",
  importFailed: "导入失败：",
  saved: "已保存 ✓",
  saveFailed: "保存失败：",
  autoName: (time: string): string => `计划 ${time}`,
  defaultBadge: "[默认]",
  moveUp: "上移",
  moveDown: "下移",
};
